version: '3.3'

networks:
  global:
    external:
      name: infrastructure_production_global

services:
  backend-core:
    image: ghcr.io/kominal/bagpack/backend-core:production
    deploy:
      replicas: 1
    networks:
      - global
    environment:
      S3_ACCESS_KEY: '$S3_ACCESS_KEY'
      S3_SECRET_KEY: '$S3_SECRET_KEY'
      S3_BUCKET: '$S3_BUCKET'
      MONGODB_CONNECTION_STRING: '$MONGODB_CONNECTION_STRING'
      MAIL_CONNECTION_STRING: '$MAIL_CONNECTION_STRING'
      SYSTEM_API_SECRET: '$SYSTEM_API_SECRET'
      AUTH0_CLIENT_ID: '$AUTH0_CLIENT_ID'
      AUTH0_CLIENT_SECRET: '$AUTH0_CLIENT_SECRET'
      JSON_WEB_TOKEN_PUBLIC_KEY: '$JSON_WEB_TOKEN_PUBLIC_KEY'
